Initial support for Python 3.11 beta
dgrunwald/rust-cpython pull request #279
Opened 2022-05-14 09:30 UTC by Techcable

This is obviously experimental but it works okay.

All the tests pass and the example prints the following:

> $ cargo run --example hello --features python-3-11
> Hello nicholas, I'm Python 3.11.0b1 (v3.11.0b1:8d32a5c8c4, May  6 2022, 22:45:29) [Clang 13.0.0 (clang-1300.0.29.30)]

I figure it's best to be proactive with these change, so that way we are ready as soon as 3.11 proper is released (October I think).

MAin difference in 3.11 that frame object is now private (and lazy loaded).
This results in a performance improvement but makes it harder for debuggers.
Also the internal ordering of code objects has completely changed as well.

2022-05-14 09:31 UTC, Techcable commented
If you want, you are free to merge right now if you want. I just figured we'd wait until 3.11 was more developed.....

2022-06-02 18:52 UTC, dgrunwald commented
We should wait for the RC which typically is ABI-compatible with the final release.
Can you rebase your branch onto the current master? I've fixed the failure with Rust 1.41.1.

2022-06-19 08:50 UTC, Techcable commented
> We should wait for the RC which typically is ABI-compatible with the final release.

I agree. We should wait to the RC before pulling this.

> Can you rebase your branch onto the current master? I've fixed the failure with Rust 1.41.1.

Done! Tests still appear to be failing though. There's something about "ast-json" on nightly

2022-09-21 21:25 UTC, dgrunwald requested changes

2022-09-21 21:25 UTC, dgrunwald commented on python3-sys/src/code.rs
> +    pub ob_base: PyObject,
Shouldn't this be PyVarObject?

2022-09-21 21:25 UTC, dgrunwald commented on python3-sys/src/code.rs
> +    pub co_warmup: c_int,
The fields around here changed since you created this pull request

2022-09-21 21:25 UTC, dgrunwald commented on python3-sys/src/code.rs
> +    pub co_weakreflist: *mut PyObject,
More fields were inserted here

2022-09-21 21:25 UTC, dgrunwald commented on python3-sys/src/code.rs
> +#[cfg(not(Py_3_11))] // TODO: Implemengt again (fields are private)
?

2022-09-21 21:25 UTC, dgrunwald commented on python3-sys/src/pyerrors.rs
> +    pub fn PyErr_SetHandledException(exc: *mut PyObject);
Missing `#[cfg(Py_3_11)]`?

2022-09-25 19:18 UTC, dgrunwald commented
I'm continuing work on python 3.11 support on https://github.com/dgrunwald/rust-cpython/tree/py3.11

2022-10-09 14:58 UTC, merged

2022-10-10 04:48 UTC, Techcable commented
Awesome! Thanks 👍